import { Cinzel } from "next/font/google";
import "./globals.scss";

const chinzel = Cinzel({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={chinzel.className}>{children}</body>
		</html>
	);
}
